# Generated by Django 6.0.3 on 2026-04-02 11:50

from django.db import migrations

def seed_schedule(apps, schema_editor):
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=1,
        period=IntervalSchedule.HOURS,
    )
    PeriodicTask.objects.get_or_create(
        name="refresh-exchange-rates",
        defaults={
            "task": "currency.fetch_rates",
            "interval": schedule,
        },
    )

def unseed_schedule(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name="refresh-exchange-rates").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("currency_exchange", "0001_initial"),
        ("django_celery_beat", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_schedule, unseed_schedule),
    ]
